### ISSUE TITLE
Dotaz ohledně obětování Arcadia Bay v 1. díle

### ISSUE THREAD

**Issue by Milhousek** [Milhousek/LifeIsStrange2#1]
![20190120163217_1](https://user-images.githubusercontent.com/34947824/51443935-ff273880-1cf0-11e9-90b5-bd8261849fe3.jpg)

Myslím, že by lépe znělo **Rozhodli jste se obětovat Arcadia Bay?**

**Comment by WartonSomik** [comment]
**Opraveno.**
