### ISSUE TITLE
Překlad výrazu "man" a jemu podobných

### ISSUE THREAD

**Issue by Milhousek** [Milhousek/LifeIsStrange2#2]
![20190120180046_1](https://user-images.githubusercontent.com/34947824/51443952-33025e00-1cf1-11e9-8594-649e41c6b492.jpg)
![20190120194733_1](https://user-images.githubusercontent.com/34947824/51443957-3eee2000-1cf1-11e9-9e92-b8554fcd29e2.jpg)

V některých případech bych vůbec výraz _man_ nepoužíval. Nezní to v češtině úplně přirozeně.

Duhý sceen = chybí háček nad E ve slově _Jasně_

**Comment by WartonSomik** [comment]
**Opraveno.**
