### ISSUE TITLE
Úkoly

### ISSUE THREAD

**Issue by Milhousek** [Milhousek/LifeIsStrange2#4]
![20190120180746_1](https://user-images.githubusercontent.com/34947824/51444002-f71bc880-1cf1-11e9-80ca-e338ad4dce03.jpg)

_Vyčistit koupelnu_ zní celkem kostrbatě. Spíš bych použil _Umýt koupelnu_ nebo _Uklidit v koupelně_

**Comment by WartonSomik** [comment]
**Opraveno.**
