### ISSUE TITLE
Recept na těstoviny

### ISSUE THREAD

**Issue by Milhousek** [Milhousek/LifeIsStrange2#5]
![20190120180931_1](https://user-images.githubusercontent.com/34947824/51444033-5bd72300-1cf2-11e9-877b-0392080c0c6d.jpg)

Těstovinov**ý** rozkoš -> Těstovinov**á** rozkoš.
Přidat polovinu lžičky s mořskou solí **->** _Přidat půlku lžičky mořské soli_ nebo _Přidat půlku kávové lžíce mořské soli_

**Comment by WartonSomik** [comment]
**Opraveno.**
